name: Tests

on:
    pull_request: null
    push:
        branches:
            - main

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['8.2', '8.3', '8.4']

        name: Tests - ${{ matrix.php_version }}
        steps:
            -   uses: actions/checkout@v4

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/phpunit
